import Head from 'next/head';
import Header from '../components/header';
import Nav from '../components/Nav';
import Result from '../components/Result';
import requests from '../utils/request';


export default function Home({results}) {
  return (
    <div >
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Nav/>
      <Result results={results}/>
    </div>
  );
}


export const getServerSideProps = async (context) => {
  const {genre} = context.query;
  const response = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)
  const data = await response.json();
  return {
    props: {
      results: data.results
    }
  }
}
